package it.poli.entity;

import it.poli.entity.generator.MyIdGenerator;
import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

@MappedSuperclass
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@SuperBuilder
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@ToString
public abstract class AbstractEntity {

  @Id
  @MyIdGenerator
  @Column(name = "Id", columnDefinition = "bigint generated by default as identity")
  @EqualsAndHashCode.Include
  private Long id;
}
